# Site settings
author: Nilan Lovelace
title: NLNLVLC - DS
header-img: img/home-bg.png
email: nilanlovelace@gmail.com
copyright_name: Nilan Lovelace
description: > # this means to ignore newlines until "baseurl:"
   
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nlnlvlc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
